### ISSUE TITLE
Help a noob

### ISSUE THREAD

**Issue by thisisnotfez** [markusdd/ilo-utils#2]
I ran the base-install script, and I got "Install local Java config to allow TLSv1.1 and disable cert checking"

What do I do?

**Comment by thisisnotfez** [comment]
Nvm, I got it. I changed the jar version from 232 to 231 (running ilo4 2.60) and it came up just fine. I have the firmware update, I just haven't gotten around to it.

**Comment by thisisnotfez** [comment]
Thank you for your efforts.

**Comment by markusdd** [comment]
Ah perfect, glad you figured it out. 
And nice that this is still useful to people!
